### ISSUE TITLE
Example from README doesnt work

### ISSUE THREAD

**Issue by Awea** [Mayeu/slugify#11]
Hi there <3

Just installed slugify using `$ curl https://slugify.now.sh > slugify && chmod +x slugify && sudo mv slugify /usr/local/bin/` successfully. But running example from README ends with an error:

```zsh
➜ echo "I'm no slug 🐌." | slugify
/usr/local/bin/slugify: 1: Syntax error: "(" unexpected
```

**Comment by Mayeu** [comment]
Solved 🎉💖
